chore(ci): disable unstable scap-related perf test from perf PR comment and check.
Signed-off-by: Federico Di Pierro <nierro92@gmail.com>

diff --git a/.github/workflows/perf.yml b/.github/workflows/perf.yml
--- a/.github/workflows/perf.yml
+++ b/.github/workflows/perf.yml
@@ -60,11 +60,12 @@ jobs:
           head -n10 "perf_tests_diff.txt" >> ./pr/COMMENT
           echo "\`\`\`" >> ./pr/COMMENT
           echo "" >> ./pr/COMMENT
-          echo "# Perf diff from master - scap file" >> ./pr/COMMENT
-          echo "\`\`\`" >> ./pr/COMMENT
-          head -n10 "perf_scap_diff.txt" >> ./pr/COMMENT
-          echo "\`\`\`" >> ./pr/COMMENT
-          echo "" >> ./pr/COMMENT
+          # Drop unstable perf results!
+          # echo "# Perf diff from master - scap file" >> ./pr/COMMENT
+          # echo "\`\`\`" >> ./pr/COMMENT
+          # head -n10 "perf_scap_diff.txt" >> ./pr/COMMENT
+          # echo "\`\`\`" >> ./pr/COMMENT
+          # echo "" >> ./pr/COMMENT
           echo "# Heap diff from master - unit tests" >> ./pr/COMMENT
           echo "\`\`\`" >> ./pr/COMMENT
           tail -n3 "heaptrack_tests_diff.txt" >> ./pr/COMMENT
@@ -98,13 +99,14 @@ jobs:
 
       # Check will fail if sum of all differences is >= 1%.
       # But we will always comment with the perf diff from master
-      - name: Check >= 1% threshold - perf scap file
-        if: always() # Even if other threshold checks failed
-        run: |
-          sum=$(awk '{sum+=sprintf("%f",$2)}END{printf "%.6f\n",sum}' perf_scap_diff.txt | tr ',' '.')
-          if (( $(echo "$sum >= 1.0" | bc -l) )); then
-            exit 1
-          fi
+      # CHECK DISABLED: UNSTABLE PERF TEST.
+#      - name: Check >= 1% threshold - perf scap file
+#        if: always() # Even if other threshold checks failed
+#        run: |
+#          sum=$(awk '{sum+=sprintf("%f",$2)}END{printf "%.6f\n",sum}' perf_scap_diff.txt | tr ',' '.')
+#          if (( $(echo "$sum >= 1.0" | bc -l) )); then
+#            exit 1
+#          fi
 
       # Check will fail if there is any heap memory usage difference >= 1M,
       # or if there is new memory leaked.
